version: '3.8'

services:
    nbs-ips-qr-app:
        build: .
        container_name: nbs-ips-qr-code
        ports:
            - '4000:4000'
            - '35729:35729' # LiveReload port
        volumes:
            - .:/app
            - bundle_cache:/usr/local/bundle
            - /app/_site
        environment:
            - JEKYLL_ENV=development
            - BUNDLE_PATH=/usr/local/bundle
        command: >
            sh -c "bundle config set --local path /usr/local/bundle &&
                   bundle config set --local deployment false &&
                   bundle install &&
                   bundle exec jekyll serve
                   -H 0.0.0.0
                   -P 4000
                   --livereload
                   --livereload-port 35729
                   --force_polling
                   --incremental"
        networks:
            - nbs-network
        restart: unless-stopped
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:4000/health.html']
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 60s

networks:
    nbs-network:
        driver: bridge

volumes:
    bundle_cache:
        driver: local
